FROM ubuntu:14.04

# PHP version
ARG PHP_VERSION=7.2
ARG PROXY_IP=172.20.128.10
ARG PROXY_PORT=3128

RUN apt-get update -q -y
RUN apt-get upgrade -q -y
RUN apt-get install -q -y valgrind git vim cmake pkg-config curl gcc g++ zlib1g-dev jq lcov iptables
RUN apt-get install -q -y  language-pack-en-base software-properties-common

ENV LC_ALL en_US.UTF-8

# Install PHP 7 from the third party repository
RUN add-apt-repository ppa:ondrej/php
RUN apt-get update -q -y
RUN apt-get install -y php${PHP_VERSION}-dev php${PHP_VERSION}-cli php${PHP_VERSION}-fpm php${PHP_VERSION}-json php${PHP_VERSION}-mysql php${PHP_VERSION}-readline

# Remove 7.1 package if 7.0 is installed
RUN /bin/bash -c 'if [[ ${PHP_VERSION} == "7.0" ]]; then apt-get -y remove php7.1-common php7.1-xml; fi'

# Install Python Connector
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py
RUN pip install -U snowflake-connector-python

COPY iptables.txt /root

# Environmet variables for tests
ENV PHP_HOME=/usr
ENV http_proxy http://${PROXY_IP}:${PROXY_PORT}
ENV https_proxy http://${PROXY_IP}:${PROXY_PORT}
ENV HTTP_PROXY http://${PROXY_IP}:${PROXY_PORT}
ENV HTTPS_PROXY http://${PROXY_IP}:${PROXY_PORT}
