/*
 * Copyright (c) 2017 Snowflake Computing, Inc. All rights reserved.
 */

#ifndef SNOWFLAKE_SNOWFLAKE_CLIENT_VERSION_H
#define SNOWFLAKE_SNOWFLAKE_CLIENT_VERSION_H

#define SF_CLIENT_VERSION "0.1.0"
#define SF_CLIENT_VERSION_ID 000100

#endif //SNOWFLAKE_SNOWFLAKE_CLIENT_VERSION_H
