/*
 * Copyright (c) 2017 Snowflake Computing, Inc. All rights reserved.
 */

#ifndef PDO_SNOWFLAKE_SNOWFLAKE_CLIENT_VERSION_H
#define PDO_SNOWFLAKE_SNOWFLAKE_CLIENT_VERSION_H

#define SNOWFLAKE_CLIENT_VERSION "0.1.0"
#define SNOWFLAKE_CLIENT_VERSION_ID 000100

#endif //PDO_SNOWFLAKE_SNOWFLAKE_CLIENT_VERSION_H
