# This is a basic workflow to help you get started with Actions

name: build_test_windows_php8-0_vs16

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [ master, simba-driverbuildtest-workflow ]
  pull_request:
    branches: [ master, simba-driverbuildtest-workflow ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    env:
      SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
      SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
      SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
      SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.SNOWFLAKE_TEST_WAREHOUSE }}
      SNOWFLAKE_TEST_DATABASE: ${{ secrets.SNOWFLAKE_TEST_DATABASE }}
      SNOWFLAKE_TEST_SCHEMA: ${{ secrets.SNOWFLAKE_TEST_SCHEMA }}
      SNOWFLAKE_TEST_ROLE: ${{ secrets.SNOWFLAKE_TEST_ROLE }}
      ARCH: x64
      TARGET: Release
      VS: VS16
      PHP: 8.0.28
      TEST_PHP_EXECUTABLE: c:\tools\php\php.exe
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: pdo, json
        env:
          phpts: ts
          
      - name: build driver
        run: python .\.github\workflows\scripts\build_driver.py
        shell: cmd
      
      
      - name: test driver
        run: python .\.github\workflows\scripts\test_driver.py
        shell: cmd
