# This is a basic workflow to help you get started with Actions

name: build_test_linux_php8-1

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [ master, simba-driverbuildtest-workflow ]
  pull_request:
    branches: [ master, simba-driverbuildtest-workflow ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
      SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
      SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
      SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.SNOWFLAKE_TEST_WAREHOUSE }}
      SNOWFLAKE_TEST_DATABASE: ${{ secrets.SNOWFLAKE_TEST_DATABASE }}
      SNOWFLAKE_TEST_SCHEMA: ${{ secrets.SNOWFLAKE_TEST_SCHEMA }}
      SNOWFLAKE_TEST_ROLE: ${{ secrets.SNOWFLAKE_TEST_ROLE }}
      REPORT_COVERAGE: 1
      PHP_HOME: /usr
      TEST_PHP_EXECUTABLE: /usr/bin/php
      NO_INTERACTION: true
      USE_VALGRIND: 0
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: setup php
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            extensions: pdo, json
            coverage: xdebug2

        - name: Setup LCOV
          run: sudo apt-get -y install lcov
          shell: bash

        #- name: setup valgrind
        #  run: |
        #    sudo apt-get install valgrind


        - name: build driver
          run: python ./.github/workflows/scripts/build_driver.py


        - name: test driver
          run: python ./.github/workflows/scripts/test_driver.py
