name: Build and Test

on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [ master, simba-driverbuildtest-workflow ]
  pull_request:
    branches: [ master, simba-driverbuildtest-workflow ]

  workflow_dispatch:

concurrency:
  # older builds for the same pull request numer or branch should be cancelled
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest, macos-latest]
        php-version: [7.4, 8.0, 8.1, 8.2]
    build-test:
        name: build-test
        runs-on: ${{ matrix.os }}
        env:
          SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
          SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
          SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
          SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.SNOWFLAKE_TEST_WAREHOUSE }}
          SNOWFLAKE_TEST_DATABASE: ${{ secrets.SNOWFLAKE_TEST_DATABASE }}
          SNOWFLAKE_TEST_SCHEMA: ${{ secrets.SNOWFLAKE_TEST_SCHEMA }}
          SNOWFLAKE_TEST_ROLE: ${{ secrets.SNOWFLAKE_TEST_ROLE }}
          PHP_HOME: /usr
          TEST_PHP_EXECUTABLE: ${{ matrix.os == 'windows-2019' && 'c:\tools\php\php.exe' || '/usr/bin/php' }}
          TARGET: Release
          VS: VS16
          PHP: ${{ matrix.php-version }}
          NO_INTERACTION: true
          USE_VALGRIND: 0
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - name: setup php
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php-version }}
                extensions: pdo, json
              env:
                phpts: ts

            - name: build driver
              run: python ./.github/workflows/scripts/build_driver.py


            - name: test driver
              run: python ./.github/workflows/scripts/test_driver.py

  code-coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
      SNOWFLAKE_TEST_PASSWORD: ${{ secrets.SNOWFLAKE_TEST_PASSWORD }}
      SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.SNOWFLAKE_TEST_ACCOUNT }}
      SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.SNOWFLAKE_TEST_WAREHOUSE }}
      SNOWFLAKE_TEST_DATABASE: ${{ secrets.SNOWFLAKE_TEST_DATABASE }}
      SNOWFLAKE_TEST_SCHEMA: ${{ secrets.SNOWFLAKE_TEST_SCHEMA }}
      SNOWFLAKE_TEST_ROLE: ${{ secrets.SNOWFLAKE_TEST_ROLE }}
      RUN_COVERAGE: 1
      PHP_HOME: /usr
      TEST_PHP_EXECUTABLE: /usr/bin/php
      NO_INTERACTION: true
      USE_VALGRIND: 0
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: setup php
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            extensions: pdo, json

        - name: build driver
          run: python ./.github/workflows/scripts/build_driver.py

        - name: test driver
          run: python ./.github/workflows/scripts/test_driver.py
